# Reference: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
# Path: ~/.config/alacritty/alacritty.yml

window:
  dynamic_title: true
  opacity: 1.0
  # Window padding (changes require restart)
  padding:
    x: 2
    y: 2
  # Window decorations
  decorations: full  # full/none/buttonless/transparent
  startup_mode: Windowed # Maximized/Windowed/Fullscreen

scrolling:
  # Maximum number of lines in the scrollback buffer, 0 to disable scrolling.
  history: 15000
  # Number of lines the viewport will move for every line scrolled when
  multiplier: 3

debug:
  # Display the time it takes to redraw each frame.
  render_timer: false

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors (Snazzy)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xeff0eb'
  cursor:
    background: '0x008ec4'
    foreground: '0xf1f1f1'
  # Normal colors
  normal:
    black:   '0x282a36'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'
  # Bright colors
  bright:
    black:   '0x686868'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'



selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

# Cursor style
cursor:
  style: Block # Block/Underline/Beam
  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

live_config_reload: true

shell:
  program: /opt/homebrew/bin/fish
