tap "homebrew/bundle"
tap "homebrew/services", "https://mirrors.ustc.edu.cn/homebrew-services.git"
tap "spring-io/tap"

brew "bash"
# brew "binutils"
brew "coreutils"
# brew "findutils"
brew "go"
brew "gradle"
brew "hugo"
brew "httpie"
brew "jq"
brew "kubectl"
brew "kubectx"
brew "k9s"
brew "maven"
brew "minikube"
# brew "moreutils"
brew "node"
brew "openjdk@21"
# brew "rename"
brew "ssh-copy-id"
brew "tree"
brew "vim"
brew "wget"

cask "1password"
cask "arc"
cask "baidunetdisk"
cask "feishu"
cask "google-chrome"
cask "intellij-idea"
cask "nvs"
cask "orbstack"
cask "switchhosts"
cask "typora"
cask "visual-studio-code"
cask "warp"
cask "wechat"
cask "zulu@8"