version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - traefik
    volumes:
      - /data/volumes/mysql:/var/lib/mysql

networks:
  traefik:
    external: true
