# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_check_update = false
  config.vm.provision :shell, :path => "bootstrap.sh"


  (1..3).each do |i|
    config.vm.define vm_name="cdh#{i}" do |config|
      config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "1024",'--cpus', 1]
          v.gui = false
      end
      config.vm.network "private_network", ip: "192.168.56.10#{i}"
      config.vm.hostname = vm_name
    end
  end
end