# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  (1..3).each do |i|
    config.vm.define vm_name = "cdh#{i}"  do |config|
		config.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "1536",'--cpus', 1]
		end
		config.vm.box = "centos6.4"
		config.vm.hostname =vm_name 
		config.ssh.username ="vagrant"
		config.ssh.password="vagrant"
		config.vm.network :private_network, ip: "192.168.56.12#{i}"
  		config.vm.provision :shell, :path => "boot.sh"
    end
  end

end
