# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos6.4"

  (1..1).each do |i|
     config.vm.define vm_name = "dev#{i}"  do |config|
	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "1024",'--cpus', 1]
	end
	config.vm.hostname =vm_name 
	config.vm.network :private_network, ip: "192.168.56.10#{i}"

	config.ssh.username = "vagrant"
	config.ssh.password="vagrant"
	config.ssh.forward_agent = true
  	config.vm.provision :shell, :path => "boot.sh"
     end
   end
end
