version: "3.7"

services:

  confluence:
    image: javachen/confluence-server:7.3.1
    ports:
      - "8090:8090"
    volumes:
      - ./data/confluence:/var/atlassian/confluence
    environment:
      - JVM_MINIMUM_MEMORY="3072m"
      - JVM_MAXIMUM_MEMORY="4096m"
      - ATL_PROXY_NAME=confluence.example.com
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=confluence
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=confluence
    restart: unless-stopped
