version: "3.7"

services:
  openldap:
    image: osixia/openldap
    container_name: openldap
    command: "--loglevel debug"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certs:/container/service/slapd/assets/certs
      - ./data/etc:/etc/ldap/slapd.d
      - ./data/var:/var/lib/ldap
      - ./data/run:/container/run
    environment:
      - LDAP_ORGANISATION=Wesine
      - LDAP_DOMAIN=wesine.com
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_BACKEND=hdb
      - LDAP_TLS=false
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
    restart: always

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    command: "--loglevel debug"
    ports:
      - "8080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    restart: always


  ldap-account-manager:
    image: ldapaccountmanager/lam:latest
    container_name: ldapaccountmanager
    restart: always
    ports:
      - "8011:80"
    environment:
      - LAM_PASSWORD=lam
      - LAM_LANG=zh_CN
      - LDAP_SERVER=ldap://openldap:389
      - LDAP_DOMAIN=wesine.com
      - LDAP_BASE_DN=dc=wesine,dc=com
      - ADMIN_USER=cn=admin,dc=wesine,dc=com
      - DEBUG=true
    depends_on:
      - openldap