# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_check_update = false

  # config.vm.provision "file", source: "files", destination: "files"

  (1..1).each do |i|
    config.vm.define vm_name="k8s-kube-node#{i}" do |node|
      node.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "4096",'--cpus', 2]
        v.gui = false
      end
      ip = "192.168.56.12#{i}"
      node.vm.network "private_network", ip: ip
      node.vm.hostname = vm_name
      node.vm.provision :shell, :path => "bootstrap.sh", args: [ip,vm_name]
    end
  end
end
