# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
cat > /etc/hosts <<EOF
192.168.56.141 gp-node001
192.168.56.142 gp-node002
192.168.56.143 gp-node003
EOF
SCRIPT
  
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant"

  (1..3).each do |i|
    config.vm.define vm_name="gp-node00#{i}" do |node|
      node.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "1024",'--cpus', 1]
        v.gui = false
      end
      ip = "192.168.56.14#{i}"
      node.vm.network "private_network", ip: ip
      node.vm.hostname = vm_name
      node.vm.provision "shell" do |s|
        s.inline = $script
      end  
      node.vm.provision :shell, :path => "bootstrap.sh", args: [ip,vm_name]
    end
  end
end
