# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_check_update = false

  # config.vm.provision "file", source: "files", destination: "files"

  config.vm.synced_folder ".", "/vagrant"

  (1..1).each do |i|
    config.vm.define vm_name="docker00#{i}" do |node|
      node.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "3072",'--cpus', 1]
        v.gui = false
      end
      ip = "192.168.56.1#{i}"
      node.vm.network "private_network", ip: ip
      node.vm.hostname = vm_name
      #node.vm.provision :shell, :path => "bootstrap.sh", args: [ip,vm_name]
      #node.vm.provision :shell,path: "https://raw.githubusercontent.com/javachen/snippets/master/bash/setup_system.sh"
      node.vm.provision :shell,path: "https://raw.githubusercontent.com/javachen/snippets/master/bash/setup_docker.sh"
    end
  end
end
